force-app/main/default/objects/CryptoExchangeRateApi__c/CryptoExchangeRateApi__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CryptoExchangeRateApi</label>
</CustomObject>

force-app/main/default/objects/CryptoExchangeRateApi__c/fields/Apikey__c.field-meta.xml
<CustomField>
    <fullName>Apikey__c</fullName>
    <label>Apikey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CurrencyExchangeRate__c/fields/Base_Currency__c.field-meta.xml
<CustomField>
    <fullName>Base_Currency__c</fullName>
    <label>Base Currency</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateCurrencyExchangeScheduleTest.cls
/**
 ==================================================================
 * @description       : Test class for UpdateCurrencyExchangeSchedule.
 * Created By         : Akshay Sharma 
 * Class Name         : UpdateCurrencyExchangeScheduleTest
 * Modifications Log 
 * Ver   Date         Author          Modification
 *
 ==================================================================
**/
@isTest
public class UpdateCurrencyExchangeScheduleTest {
     @testSetup
    static void setupTestData(){
        CryptoExchangeRateApi__c apiDet = new CryptoExchangeRateApi__c();
        apiDet.Apikey__c = 'a8b9feee4ecc38eb44e478a614e9ae1c338b71baa0412330d313d049633c76c4';
        apiDet.Endpoint__c = 'https://min-api.cryptocompare.com/data/price';
        insert apiDet;
        
        CurrencyExchangeRate__c exchrec = new CurrencyExchangeRate__c();
        exchrec.Base_Currency__c = 'USD';
        insert exchrec;
        
    }
    
    @isTest
    static void testSchedule(){
        Test.setMock(HttpCalloutMock.class, new CurrencyExchangeControllerMock());
        Test.startTest();
        String sch = '0 0 23 * * ?'; 
        system.schedule('Currency Exchange Schedule', sch, new UpdateCurrencyExchangeSchedule());
        Test.stopTest();
    }

}